### ISSUE TITLE
Can the target FPS be adjusted manually?

### ISSUE THREAD

**Issue by IzuhaRui** [Erimelowo/OpenVR-Dynamic-Resolution#44]
Even if I turn on alwaysReproject, the target FPS is still 36. Because in VRCHAT, 36FPS is too high. I want to start adjusting the resolution at 20fps. 20-30FPS, hold the resolution. Above 30FPS, increase the resolution.
    This software is very great. I used to adjust the resolution manually, but it gives me hope for automation.

**Comment by Erimelowo** [comment]
![OVR-Dynamic-Resolution_3628zWSq6j](https://github.com/user-attachments/assets/d88fd406-1e0c-465e-9759-37d79db6e09c)

You can change the Increase/Decrease thresholds to do that. For example, while "Always reproject" is off and "Ignore CPU time" is on, setting the Increase scale to 26 and the decrease scale to 30 or so should target 24 FPS in your case.

Closing this as I don't plan to add a way to target a specific FPS since that wouldn't work as you'd expect it (you'd be stuck at 1/2, 1/3 or 1/4 of the HMD hz), so "Always reproject" being on is enough for most people imo and changing the thresholds works for the others.
